{{- if lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "mongodbcommunity.mongodbcommunity.mongodb.com" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-community-database.fullname" . }}-credentials
  labels:
    {{- include "mongodb-community-database.labels" . | nindent 4 }}
type: Opaque
data:
{{- range .Values.mongodb.users }}
  {{ .name }}-password: {{ .password | b64enc }}
{{- end }}
{{- end }}
