{{- if and .Values.serviceAccount.create (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "mongodbcommunity.mongodbcommunity.mongodb.com") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mongodb-community-database.serviceAccountName" . }}
  labels:
    {{- include "mongodb-community-database.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
